name = "football-stats-ai"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Cloudflare Pages configuration
[build]
command = "npm run build"

# Environment variables (set these in Cloudflare Dashboard)
# [env.production.vars]
# Add your environment variables here or in the Cloudflare dashboard
